version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Sff-backend
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_install.sh
      timeout: 300
      runas: root
